### ISSUE TITLE
Inquiry about Data Sets for Natural Gas Compressibility Factor Modeling

### ISSUE THREAD

**Issue by NgBlaze** [Dseal95/AGA8_Detail#1]
Hello, @Dseal95 

I hope this message finds you well. I'm currently working on a machine learning project focused on natural gas compressibility factor modeling. Your repository on this topic has caught my attention, and I'm impressed by the work you've done.
I am reaching out to kindly inquire about the data sets you used for creating your model. I believe that having access to these data sets would greatly assist me in my project. I want to assure you that I take data confidentiality seriously, and any data shared with me will be kept strictly confidential and used solely for academic purposes.
If it's possible to share the data sets or provide any guidance on where I might find relevant data, I would greatly appreciate it. Your assistance would be invaluable in advancing my project.
Thank you for your time and consideration. Looking forward to your response.

Best regards

**Comment by Dseal95** [comment]
Hi @NgBlaze, 

Thanks for getting in touch. 

In terms of creating my model, I simply converted the C AGA8 code from https://github.com/usnistgov/AGA8 and used the example from the detail test to test my Python implementation (https://github.com/usnistgov/AGA8/blob/master/AGA8CODE/C/Detail_test_01.cpp). I have also downloaded the test data from that repo as well and made sure that I was able to get the same result as the C implementation but I have only done this locally. There are some other tests in my repo that I got directly from a simulation done by an engineer in UniSim. This was the only "ground truth" I had available when implementing this code.

If you want the test data, you can grab it directly from that repo. The author is happy for people to code up "community" implementations in other languages. 

Let me know if that helps,
Dan

**Comment by NgBlaze** [comment]
Thank you for your prompt response and the valuable information you provided. I truly appreciate your assistance and insights.
I've successfully retrieved the data from the repository you mentioned.
As my machine learning project progresses, I'll definitely keep you updated on the outcomes and any advancements I make. Your expertise and input would be highly valuable, and I'm optimistic about the potential for collaboration in the future. It's exciting to think about the possibilities of working together on "community" implementations in various languages.
Once again, thank you for your support. I look forward to staying in touch and exploring opportunities for collaboration.


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Dseal95** [comment]
Good luck and I look forward to hearing from you
