### ISSUE TITLE
PropertiesDetail() implemented or not?

### ISSUE THREAD

**Issue by philip-lindner** [Dseal95/AGA8_Detail#2]
Hi @Dseal95 ,

first of all: Thanks for sharing your Python Implementation! This could be of great use for my project! 

There is just one thing I do not understand: In the README it says, that PropertiesDetail() is not implemented because you were only interested in Z. However, I do see the function  properties_detail() defined in AGA8Detail.py . In addition, I see that the the output of cv,cp, and other quantities are tested in test_AGA8Detail.py. 

Could you clarify whether properties_detail() is implemented and the respective parameters can be used?

Best regards,
Philip

**Comment by Dseal95** [comment]
Hi Philip,

That’s a good spot. Initially I hadn’t implemented it but later did and I
forgot to update the README.md.

It is implemented and will be run automatically after executing the run()
method.

Regards,
Dan
